import { RequestHandler } from "express";

// Cache for branches data
let branchesCache: any[] = [];
let cacheExpiry = 0;
const CACHE_DURATION = 24 * 60 * 60 * 1000; // 24 hours

export const getBranches: RequestHandler = async (req, res) => {
  try {
    // Check cache first
    if (branchesCache.length > 0 && Date.now() < cacheExpiry) {
      return res.json({ branches: branchesCache });
    }

    const branches = [
      // 1. Arts & Humanities
      { id: "arts-humanities", category: "Arts & Humanities", name: "Arts & Humanities" },
      { id: "english-literature", category: "Arts & Humanities", name: "English Literature" },
      { id: "history", category: "Arts & Humanities", name: "History" },
      { id: "philosophy", category: "Arts & Humanities", name: "Philosophy" },
      { id: "religious-studies", category: "Arts & Humanities", name: "Religious Studies" },
      { id: "languages", category: "Arts & Humanities", name: "Languages" },
      { id: "linguistics", category: "Arts & Humanities", name: "Linguistics" },
      { id: "classics", category: "Arts & Humanities", name: "Classics" },
      { id: "archaeology", category: "Arts & Humanities", name: "Archaeology" },
      { id: "anthropology", category: "Arts & Humanities", name: "Anthropology" },
      { id: "cultural-studies", category: "Arts & Humanities", name: "Cultural Studies" },
      { id: "media-studies", category: "Arts & Humanities", name: "Media Studies" },
      { id: "film-studies", category: "Arts & Humanities", name: "Film Studies" },
      { id: "theater-arts", category: "Arts & Humanities", name: "Theater Arts" },
      { id: "music", category: "Arts & Humanities", name: "Music" },
      { id: "fine-arts", category: "Arts & Humanities", name: "Fine Arts" },
      { id: "design", category: "Arts & Humanities", name: "Design" },
      { id: "creative-writing", category: "Arts & Humanities", name: "Creative Writing" },

      // 2. Social Sciences
      { id: "social-sciences", category: "Social Sciences", name: "Social Sciences" },
      { id: "psychology", category: "Social Sciences", name: "Psychology" },
      { id: "sociology", category: "Social Sciences", name: "Sociology" },
      { id: "political-science", category: "Social Sciences", name: "Political Science" },
      { id: "economics", category: "Social Sciences", name: "Economics" },
      { id: "geography", category: "Social Sciences", name: "Geography" },
      { id: "international-relations", category: "Social Sciences", name: "International Relations" },
      { id: "public-policy", category: "Social Sciences", name: "Public Policy" },
      { id: "social-work", category: "Social Sciences", name: "Social Work" },
      { id: "criminology", category: "Social Sciences", name: "Criminology" },
      { id: "gender-studies", category: "Social Sciences", name: "Gender Studies" },
      { id: "development-studies", category: "Social Sciences", name: "Development Studies" },
      { id: "urban-studies", category: "Social Sciences", name: "Urban Studies" },
      { id: "environmental-studies", category: "Social Sciences", name: "Environmental Studies" },

      // 3. Business & Management
      { id: "business-management", category: "Business & Management", name: "Business & Management" },
      { id: "business-administration", category: "Business & Management", name: "Business Administration" },
      { id: "accounting", category: "Business & Management", name: "Accounting" },
      { id: "finance", category: "Business & Management", name: "Finance" },
      { id: "marketing", category: "Business & Management", name: "Marketing" },
      { id: "human-resources", category: "Business & Management", name: "Human Resources" },
      { id: "operations-management", category: "Business & Management", name: "Operations Management" },
      { id: "supply-chain-management", category: "Business & Management", name: "Supply Chain Management" },
      { id: "project-management", category: "Business & Management", name: "Project Management" },
      { id: "entrepreneurship", category: "Business & Management", name: "Entrepreneurship" },
      { id: "international-business", category: "Business & Management", name: "International Business" },
      { id: "real-estate", category: "Business & Management", name: "Real Estate" },
      { id: "hospitality-management", category: "Business & Management", name: "Hospitality Management" },
      { id: "tourism-management", category: "Business & Management", name: "Tourism Management" },
      { id: "retail-management", category: "Business & Management", name: "Retail Management" },
      { id: "logistics", category: "Business & Management", name: "Logistics" },
      { id: "e-commerce", category: "Business & Management", name: "E-commerce" },

      // 4. Engineering & Technology
      { id: "engineering-technology", category: "Engineering & Technology", name: "Engineering & Technology" },
      { id: "computer-science", category: "Engineering & Technology", name: "Computer Science" },
      { id: "software-engineering", category: "Engineering & Technology", name: "Software Engineering" },
      { id: "information-technology", category: "Engineering & Technology", name: "Information Technology" },
      { id: "data-science", category: "Engineering & Technology", name: "Data Science" },
      { id: "artificial-intelligence", category: "Engineering & Technology", name: "Artificial Intelligence" },
      { id: "machine-learning", category: "Engineering & Technology", name: "Machine Learning" },
      { id: "cybersecurity", category: "Engineering & Technology", name: "Cybersecurity" },
      { id: "network-engineering", category: "Engineering & Technology", name: "Network Engineering" },
      { id: "web-development", category: "Engineering & Technology", name: "Web Development" },
      { id: "mobile-development", category: "Engineering & Technology", name: "Mobile Development" },
      { id: "game-development", category: "Engineering & Technology", name: "Game Development" },
      { id: "robotics", category: "Engineering & Technology", name: "Robotics" },
      { id: "mechanical-engineering", category: "Engineering & Technology", name: "Mechanical Engineering" },
      { id: "electrical-engineering", category: "Engineering & Technology", name: "Electrical Engineering" },
      { id: "civil-engineering", category: "Engineering & Technology", name: "Civil Engineering" },
      { id: "chemical-engineering", category: "Engineering & Technology", name: "Chemical Engineering" },
      { id: "biomedical-engineering", category: "Engineering & Technology", name: "Biomedical Engineering" },
      { id: "aerospace-engineering", category: "Engineering & Technology", name: "Aerospace Engineering" },
      { id: "environmental-engineering", category: "Engineering & Technology", name: "Environmental Engineering" },
      { id: "industrial-engineering", category: "Engineering & Technology", name: "Industrial Engineering" },
      { id: "materials-engineering", category: "Engineering & Technology", name: "Materials Engineering" },
      { id: "nuclear-engineering", category: "Engineering & Technology", name: "Nuclear Engineering" },
      { id: "petroleum-engineering", category: "Engineering & Technology", name: "Petroleum Engineering" },
      { id: "mining-engineering", category: "Engineering & Technology", name: "Mining Engineering" },
      { id: "telecommunications", category: "Engineering & Technology", name: "Telecommunications" },
      { id: "biotechnology", category: "Engineering & Technology", name: "Biotechnology" },
      { id: "nanotechnology", category: "Engineering & Technology", name: "Nanotechnology" },

      // 5. Medical & Health Sciences
      { id: "medical-health-sciences", category: "Medical & Health Sciences", name: "Medical & Health Sciences" },
      { id: "medicine", category: "Medical & Health Sciences", name: "Medicine" },
      { id: "nursing", category: "Medical & Health Sciences", name: "Nursing" },
      { id: "pharmacy", category: "Medical & Health Sciences", name: "Pharmacy" },
      { id: "dentistry", category: "Medical & Health Sciences", name: "Dentistry" },
      { id: "physiotherapy", category: "Medical & Health Sciences", name: "Physiotherapy" },
      { id: "occupational-therapy", category: "Medical & Health Sciences", name: "Occupational Therapy" },
      { id: "speech-therapy", category: "Medical & Health Sciences", name: "Speech Therapy" },
      { id: "radiology", category: "Medical & Health Sciences", name: "Radiology" },
      { id: "laboratory-sciences", category: "Medical & Health Sciences", name: "Laboratory Sciences" },
      { id: "public-health", category: "Medical & Health Sciences", name: "Public Health" },
      { id: "epidemiology", category: "Medical & Health Sciences", name: "Epidemiology" },
      { id: "nutrition", category: "Medical & Health Sciences", name: "Nutrition" },
      { id: "dietetics", category: "Medical & Health Sciences", name: "Dietetics" },
      { id: "veterinary-medicine", category: "Medical & Health Sciences", name: "Veterinary Medicine" },
      { id: "optometry", category: "Medical & Health Sciences", name: "Optometry" },
      { id: "chiropractic", category: "Medical & Health Sciences", name: "Chiropractic" },
      { id: "osteopathy", category: "Medical & Health Sciences", name: "Osteopathy" },
      { id: "homeopathy", category: "Medical & Health Sciences", name: "Homeopathy" },
      { id: "ayurveda", category: "Medical & Health Sciences", name: "Ayurveda" },
      { id: "traditional-chinese-medicine", category: "Medical & Health Sciences", name: "Traditional Chinese Medicine" },
      { id: "mental-health", category: "Medical & Health Sciences", name: "Mental Health" },
      { id: "psychiatry", category: "Medical & Health Sciences", name: "Psychiatry" },
      { id: "clinical-psychology", category: "Medical & Health Sciences", name: "Clinical Psychology" },

      // 6. Natural Sciences
      { id: "natural-sciences", category: "Natural Sciences", name: "Natural Sciences" },
      { id: "physics", category: "Natural Sciences", name: "Physics" },
      { id: "chemistry", category: "Natural Sciences", name: "Chemistry" },
      { id: "biology", category: "Natural Sciences", name: "Biology" },
      { id: "mathematics", category: "Natural Sciences", name: "Mathematics" },
      { id: "statistics", category: "Natural Sciences", name: "Statistics" },
      { id: "astronomy", category: "Natural Sciences", name: "Astronomy" },
      { id: "geology", category: "Natural Sciences", name: "Geology" },
      { id: "meteorology", category: "Natural Sciences", name: "Meteorology" },
      { id: "oceanography", category: "Natural Sciences", name: "Oceanography" },
      { id: "botany", category: "Natural Sciences", name: "Botany" },
      { id: "zoology", category: "Natural Sciences", name: "Zoology" },
      { id: "microbiology", category: "Natural Sciences", name: "Microbiology" },
      { id: "genetics", category: "Natural Sciences", name: "Genetics" },
      { id: "biochemistry", category: "Natural Sciences", name: "Biochemistry" },
      { id: "molecular-biology", category: "Natural Sciences", name: "Molecular Biology" },
      { id: "ecology", category: "Natural Sciences", name: "Ecology" },
      { id: "environmental-science", category: "Natural Sciences", name: "Environmental Science" },
      { id: "marine-science", category: "Natural Sciences", name: "Marine Science" },
      { id: "atmospheric-science", category: "Natural Sciences", name: "Atmospheric Science" },
      { id: "earth-science", category: "Natural Sciences", name: "Earth Science" },
      { id: "paleontology", category: "Natural Sciences", name: "Paleontology" },
      { id: "neuroscience", category: "Natural Sciences", name: "Neuroscience" },
      { id: "immunology", category: "Natural Sciences", name: "Immunology" },
      { id: "pharmacology", category: "Natural Sciences", name: "Pharmacology" },
      { id: "toxicology", category: "Natural Sciences", name: "Toxicology" },

      // 7. Education
      { id: "education", category: "Education", name: "Education" },
      { id: "early-childhood-education", category: "Education", name: "Early Childhood Education" },
      { id: "primary-education", category: "Education", name: "Primary Education" },
      { id: "secondary-education", category: "Education", name: "Secondary Education" },
      { id: "special-education", category: "Education", name: "Special Education" },
      { id: "adult-education", category: "Education", name: "Adult Education" },
      { id: "educational-leadership", category: "Education", name: "Educational Leadership" },
      { id: "curriculum-development", category: "Education", name: "Curriculum Development" },
      { id: "educational-technology", category: "Education", name: "Educational Technology" },
      { id: "educational-psychology", category: "Education", name: "Educational Psychology" },
      { id: "counseling", category: "Education", name: "Counseling" },
      { id: "school-administration", category: "Education", name: "School Administration" },
      { id: "higher-education", category: "Education", name: "Higher Education" },
      { id: "distance-learning", category: "Education", name: "Distance Learning" },
      { id: "librarianship", category: "Education", name: "Librarianship" },
      { id: "information-science", category: "Education", name: "Information Science" },

      // 8. Law & Legal Studies
      { id: "law-legal-studies", category: "Law & Legal Studies", name: "Law & Legal Studies" },
      { id: "law", category: "Law & Legal Studies", name: "Law" },
      { id: "criminal-law", category: "Law & Legal Studies", name: "Criminal Law" },
      { id: "civil-law", category: "Law & Legal Studies", name: "Civil Law" },
      { id: "constitutional-law", category: "Law & Legal Studies", name: "Constitutional Law" },
      { id: "international-law", category: "Law & Legal Studies", name: "International Law" },
      { id: "human-rights-law", category: "Law & Legal Studies", name: "Human Rights Law" },
      { id: "environmental-law", category: "Law & Legal Studies", name: "Environmental Law" },
      { id: "intellectual-property-law", category: "Law & Legal Studies", name: "Intellectual Property Law" },
      { id: "corporate-law", category: "Law & Legal Studies", name: "Corporate Law" },
      { id: "tax-law", category: "Law & Legal Studies", name: "Tax Law" },
      { id: "family-law", category: "Law & Legal Studies", name: "Family Law" },
      { id: "labor-law", category: "Law & Legal Studies", name: "Labor Law" },
      { id: "health-law", category: "Law & Legal Studies", name: "Health Law" },
      { id: "cyber-law", category: "Law & Legal Studies", name: "Cyber Law" },
      { id: "legal-studies", category: "Law & Legal Studies", name: "Legal Studies" },
      { id: "criminology", category: "Law & Legal Studies", name: "Criminology" },
      { id: "forensic-science", category: "Law & Legal Studies", name: "Forensic Science" },

      // 9. Agriculture & Food Sciences
      { id: "agriculture-food-sciences", category: "Agriculture & Food Sciences", name: "Agriculture & Food Sciences" },
      { id: "agriculture", category: "Agriculture & Food Sciences", name: "Agriculture" },
      { id: "agricultural-science", category: "Agriculture & Food Sciences", name: "Agricultural Science" },
      { id: "agronomy", category: "Agriculture & Food Sciences", name: "Agronomy" },
      { id: "horticulture", category: "Agriculture & Food Sciences", name: "Horticulture" },
      { id: "animal-science", category: "Agriculture & Food Sciences", name: "Animal Science" },
      { id: "dairy-science", category: "Agriculture & Food Sciences", name: "Dairy Science" },
      { id: "poultry-science", category: "Agriculture & Food Sciences", name: "Poultry Science" },
      { id: "fisheries-science", category: "Agriculture & Food Sciences", name: "Fisheries Science" },
      { id: "forestry", category: "Agriculture & Food Sciences", name: "Forestry" },
      { id: "wildlife-management", category: "Agriculture & Food Sciences", name: "Wildlife Management" },
      { id: "soil-science", category: "Agriculture & Food Sciences", name: "Soil Science" },
      { id: "food-science", category: "Agriculture & Food Sciences", name: "Food Science" },
      { id: "food-technology", category: "Agriculture & Food Sciences", name: "Food Technology" },
      { id: "nutrition-science", category: "Agriculture & Food Sciences", name: "Nutrition Science" },
      { id: "agricultural-economics", category: "Agriculture & Food Sciences", name: "Agricultural Economics" },
      { id: "rural-development", category: "Agriculture & Food Sciences", name: "Rural Development" },
      { id: "agricultural-engineering", category: "Agriculture & Food Sciences", name: "Agricultural Engineering" },
      { id: "sustainable-agriculture", category: "Agriculture & Food Sciences", name: "Sustainable Agriculture" },
      { id: "organic-farming", category: "Agriculture & Food Sciences", name: "Organic Farming" },

      // 10. Architecture & Design
      { id: "architecture-design", category: "Architecture & Design", name: "Architecture & Design" },
      { id: "architecture", category: "Architecture & Design", name: "Architecture" },
      { id: "interior-design", category: "Architecture & Design", name: "Interior Design" },
      { id: "landscape-architecture", category: "Architecture & Design", name: "Landscape Architecture" },
      { id: "urban-planning", category: "Architecture & Design", name: "Urban Planning" },
      { id: "regional-planning", category: "Architecture & Design", name: "Regional Planning" },
      { id: "industrial-design", category: "Architecture & Design", name: "Industrial Design" },
      { id: "product-design", category: "Architecture & Design", name: "Product Design" },
      { id: "graphic-design", category: "Architecture & Design", name: "Graphic Design" },
      { id: "fashion-design", category: "Architecture & Design", name: "Fashion Design" },
      { id: "textile-design", category: "Architecture & Design", name: "Textile Design" },
      { id: "jewelry-design", category: "Architecture & Design", name: "Jewelry Design" },
      { id: "furniture-design", category: "Architecture & Design", name: "Furniture Design" },
      { id: "lighting-design", category: "Architecture & Design", name: "Lighting Design" },
      { id: "exhibition-design", category: "Architecture & Design", name: "Exhibition Design" },
      { id: "set-design", category: "Architecture & Design", name: "Set Design" },
      { id: "costume-design", category: "Architecture & Design", name: "Costume Design" },
      { id: "digital-design", category: "Architecture & Design", name: "Digital Design" },
      { id: "web-design", category: "Architecture & Design", name: "Web Design" },
      { id: "game-design", category: "Architecture & Design", name: "Game Design" },
      { id: "animation", category: "Architecture & Design", name: "Animation" },
      { id: "visual-effects", category: "Architecture & Design", name: "Visual Effects" },

      // 11. Communication & Media
      { id: "communication-media", category: "Communication & Media", name: "Communication & Media" },
      { id: "communication", category: "Communication & Media", name: "Communication" },
      { id: "journalism", category: "Communication & Media", name: "Journalism" },
      { id: "broadcasting", category: "Communication & Media", name: "Broadcasting" },
      { id: "public-relations", category: "Communication & Media", name: "Public Relations" },
      { id: "advertising", category: "Communication & Media", name: "Advertising" },
      { id: "marketing-communication", category: "Communication & Media", name: "Marketing Communication" },
      { id: "digital-media", category: "Communication & Media", name: "Digital Media" },
      { id: "multimedia", category: "Communication & Media", name: "Multimedia" },
      { id: "film-production", category: "Communication & Media", name: "Film Production" },
      { id: "television-production", category: "Communication & Media", name: "Television Production" },
      { id: "radio-production", category: "Communication & Media", name: "Radio Production" },
      { id: "photography", category: "Communication & Media", name: "Photography" },
      { id: "cinematography", category: "Communication & Media", name: "Cinematography" },
      { id: "sound-design", category: "Communication & Media", name: "Sound Design" },
      { id: "editing", category: "Communication & Media", name: "Editing" },
      { id: "scriptwriting", category: "Communication & Media", name: "Scriptwriting" },
      { id: "content-creation", category: "Communication & Media", name: "Content Creation" },
      { id: "social-media", category: "Communication & Media", name: "Social Media" },
      { id: "digital-marketing", category: "Communication & Media", name: "Digital Marketing" },
      { id: "brand-management", category: "Communication & Media", name: "Brand Management" },
      { id: "event-management", category: "Communication & Media", name: "Event Management" },
      { id: "sports-communication", category: "Communication & Media", name: "Sports Communication" },
      { id: "political-communication", category: "Communication & Media", name: "Political Communication" },
      { id: "health-communication", category: "Communication & Media", name: "Health Communication" },
      { id: "environmental-communication", category: "Communication & Media", name: "Environmental Communication" }
    ];

    // Cache the data
    branchesCache = branches;
    cacheExpiry = Date.now() + CACHE_DURATION;

    res.json({ branches });
  } catch (error) {
    console.error("Error fetching branches:", error);
    res.status(500).json({ error: "Failed to fetch branches" });
  }
};
